In [56]:
# download necessary NLTK data
import nltk
nltk.download(['punkt', 'wordnet'])

# import statements
import re
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

[nltk_data] Downloading package punkt to /Users/ryanneal/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/ryanneal/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [57]:
def load_data():
    df = pd.read_csv('corporate_messaging.csv', encoding='latin-1')
    df = df[(df["category:confidence"] == 1) & (df['category'] != 'Exclude')]
    X = df.text.values
    y = df.category.values
    return X, y

In [58]:
url_regex = ('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')

In [59]:
def tokenize(text):
    # get list of all urls using regex
    detected_urls = re.findall(url_regex, text)
    
    # replace each url in text string with placeholder
    for url in detected_urls:
        text = text.replace(url, "urlplaceholder")

    # tokenize text
    tokens = word_tokenize(text)
    
    # initiate lemmatizer
    lemmatizer = wordnet_lemmatizer = WordNetLemmatizer()

    # iterate through each token
    clean_tokens = []
    for tok in tokens:
        
        # lemmatize, normalize case, and remove leading/trailing white space
        clean_tok = lemmatizer.lemmatize(tok).lower().strip()
        clean_tokens.append(clean_tok)

    return clean_tokens

<h2> Machine Learning Model </h2>

In [60]:
def display_results(y_test, y_pred):
    labels = np.unique(y_pred)
    confusion_mat = confusion_matrix(y_test, y_pred, labels=labels)
    accuracy = (y_pred == y_test).mean()

    print("Labels:", labels)
    print("Confusion Matrix:\n", confusion_mat)
    print("Accuracy:", accuracy)

In [61]:
def manual_main():
    # load data into model
    X, y = load_data()

    # perform train test split. Save 30 percent of data for testing.
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3)
    
    # initialize objects we need
    vect = CountVectorizer(tokenizer=tokenize) 
    tfidf = TfidfTransformer()
    clf = RandomForestClassifier()
    
    # get word counts using count vectorizer
    X_train_word_count = vect.fit_transform(X_train)
    # calculate word frequency using tfidf and count vector results
    tfidf_train = tfidf.fit_transform(X_train_word_count)
    # fit with a random forest model
    clf.fit(tfidf_train, y_train)
    
    # Transform test data
    X_test_word_count = vect.transform(X_test)
    tfidf_test = tfidf.transform(X_test_word_count)
    #predict y value with random forest model
    y_pred = clf.predict(tfidf_test)
    
    display_results(y_test, y_pred)

In [62]:
def main():
    X, y = load_data()
    X_train, X_test, y_train, y_test = train_test_split(X, y)

    # build pipeline
    pipeline = Pipeline([('vect', CountVectorizer()),
                        ('tfidf', TfidfTransformer()),
                        ('clf', RandomForestClassifier())])

      
        
    # train classifier
    pipeline.fit(X_train, y_train)
    
    # predict on test data
    y_pred = pipeline.predict(X_test)
    # display results
    display_results(y_test, y_pred)

In [63]:
main()

Labels: ['Action' 'Dialogue' 'Information']
Confusion Matrix:
 [[ 88   0  17]
 [  0  23   8]
 [  2   1 462]]
Accuracy: 0.9534109816971714
